version: "3.8"

networks:
  db-net:
    driver: bridge

services:
  demo-db:
    container_name: demo-db
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    networks:
      - db-net
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --range_optimizer_max_mem_size=16777216
    environment:
      MYSQL_DATABASE : demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      MYSQL_ROOT_PASSWORD: demo

  demo-nginx:
    container_name: demo-nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443"
    networks:
      - db-net
    environment:
      - TZ=Asia/Seoul
